export default Object.freeze({
    LISTING_DETAILS: "ListingDetails",
    LISTING_EDIT: "ListingEdit",
    LOGIN: "Login",
    MESSAGES: "Messages",
    REGISTER: "Register",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    CATEGORY_SELECT: "CategorySelect",
    CONFIRM_ACCOUNT: "ConfirmAccount",
    HomeScene: "HomeScene",
    HomeDetails: "HomeDetails",
    TabSearch: "TAB_SEARCH",
    TabHome: "TAB_HOME",
    TabLibrary: "TAB_LIBRARY",
    TabProfile: "TAB_PROFILE",
});
